apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: ticket-backend
spec:
  containers:
  - name: ticket-backend-container
    image: foobarfarm/ticket-backend:0.1.0
    ports:
    - containerPort: 80
    env:
    - name: DB_URI
      value: "foo"