apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: ticket-backend
spec:
  containers:
  - name: ticket-backend-container
    image: foobarfarm/ticket-backend:0.1.8
    ports:
    - containerPort: 8080
    env:
    - name: ACTIVE_PROFILE
      value: "prod"
    - name: DB_URI
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: hostname
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
