apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: ticket-frontend
spec:
  containers:
  - name: ticket-frontend-container
    image: foobarfarm/ticket-frontend:0.1.1
    ports:
    - containerPort: 80
    env:
    - name: DB_URI
      value: "foo"