apiVersion: v1
kind: Pod
metadata:
  name: nginx-reverse-proxy
  labels:
    app: nginx-reverse-proxy
spec:
  containers:
  - name: nginx-reverse-proxy-container
    image: foobarfarm/nginx-reverse-proxy:0.1.4
    ports:
    - containerPort: 80